// должен будет уметь работать с фильтрами и запрашивать данные с сервера

import {fill} from '@/js/cards.js';
// Если это первая страница, скрываем сортировку по цене
if (location.pathname === '/') document.querySelector('.type_views.coin').style.display = 'none'

// в зависимости от страницы, запрашиваем нужные данные

console.log('location.pathname = ', location.pathname)

let cars
if (location.pathname === '/') {
    cars = [
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
    ]
} else if (location.pathname === '/cars/') {
    cars = [
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
    ]
} else {
    cars = [
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/1/p1.jpg',
                '/photo-offers/1/p2.jpg',
                '/photo-offers/1/p3.jpg',
                '/photo-offers/1/p4.jpg',
                '/photo-offers/1/p5.jpg',
                '/photo-offers/1/p6.jpg']
        },
        {
            address: 'Набережные Челны, Мусы Джалиля 15',
            name: 'Volkswagen Polo, 2014',
            href: '/cars/polo/649868/',
            price: '784 238',
            fromPerMonth: '8 700',
            info: '133&nbsp;055 км, 1.6 MT (85 л.с), седан, передний, бензин',
            photos: ['/photo-offers/2/p1.jpg',
                '/photo-offers/2/p2.jpg',
                '/photo-offers/2/p3.jpg',
                '/photo-offers/2/p4.jpg',
                '/photo-offers/2/p5.jpg',
                '/photo-offers/2/p6.jpg']
        },

    ]
}


fill(cars)